name: Hola mundo with triggers
run-name: Realizando un hola mundo con triggers
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
    paths:
      - '**.js'
  issues:
    types:
      - labeled
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 17
      - name: Correr script
        run: node hola.js